import 'package:test/test.dart';
import 'package:starcitizen_wiki_api/starcitizen_wiki_api.dart';

// tests for GameItem
void main() {
  final GameItem? instance = /* GameItem(...) */ null;
  // TODO add properties to the entity

  group(GameItem, () {
    // Unique identifier of the item.
    // String uuid
    test('to test the property `uuid`', () async {
      // TODO
    });

    // URL-friendly slug for the item.
    // String slug
    test('to test the property `slug`', () async {
      // TODO
    });

    // Display name of the item.
    // String name
    test('to test the property `name`', () async {
      // TODO
    });

    // Internal class name of the item definition.
    // String className
    test('to test the property `className`', () async {
      // TODO
    });

    // Classification generated by ScDataDumper.
    // String classification
    test('to test the property `classification`', () async {
      // TODO
    });

    // Human-readable label for the item classification
    // String classificationLabel
    test('to test the property `classificationLabel`', () async {
      // TODO
    });

    // GameItemDescription description
    test('to test the property `description`', () async {
      // TODO
    });

    // Item size from AttachDef. Vehicle items range 1-12, FPS items are smaller.
    // int size
    test('to test the property `size`', () async {
      // TODO
    });

    // Physical mass in kilograms from SEntityRigidPhysicsControllerParams.
    // double mass
    test('to test the property `mass`', () async {
      // TODO
    });

    // Item rarity from stdItem.Rarity. Only present when the item has rarity data.
    // String rarity
    test('to test the property `rarity`', () async {
      // TODO
    });

    // Event or reward source labels for limited/event items. Empty for regular items.
    // List<String> eventSource
    test('to test the property `eventSource`', () async {
      // TODO
    });

    // Whether this item is the base variant (has no parent variant).
    // bool isBaseVariant
    test('to test the property `isBaseVariant`', () async {
      // TODO
    });

    // Whether this item can be crafted via blueprints.
    // bool isCraftable
    test('to test the property `isCraftable`', () async {
      // TODO
    });

    // Crafting blueprints that produce this item. Only returned when the item is craftable. Use include=blueprints to get full blueprint data instead of links.
    // List<GameItemBlueprintInner> blueprint
    test('to test the property `blueprint`', () async {
      // TODO
    });

    // Only returned for Ship.* items (derived formatting for ship grades).
    // String grade
    test('to test the property `grade`', () async {
      // TODO
    });

    // Only returned for Ship.* items.
    // String class_
    test('to test the property `class_`', () async {
      // TODO
    });

    // Key/value pairs derived from the item description.
    // List<ItemDescriptionData> descriptionData
    test('to test the property `descriptionData`', () async {
      // TODO
    });

    // Manufacturer name extracted from the description data entries.
    // String manufacturerDescription
    test('to test the property `manufacturerDescription`', () async {
      // TODO
    });

    // ManufacturerLink manufacturer
    test('to test the property `manufacturer`', () async {
      // TODO
    });

    // Item type identifier (NOITEM_ prefix removed), e.g. Weapon, Armor, Clothing.
    // String type
    test('to test the property `type`', () async {
      // TODO
    });

    // Human-readable label for the item type
    // String typeLabel
    test('to test the property `typeLabel`', () async {
      // TODO
    });

    // Web URL for filtering items by type
    // String typeWebUrl
    test('to test the property `typeWebUrl`', () async {
      // TODO
    });

    // Item sub-type identifier, e.g. Small, Medium, Rocket.
    // String subType
    test('to test the property `subType`', () async {
      // TODO
    });

    // Human-readable label for the item sub-type
    // String subTypeLabel
    test('to test the property `subTypeLabel`', () async {
      // TODO
    });

    // Only returned for WeaponAttachment items (non-placeholder). Maps sub_type to a display slot name.
    // String position
    test('to test the property `position`', () async {
      // TODO
    });

    // Only returned for turret-like items.
    // int maxMounts
    test('to test the property `maxMounts`', () async {
      // TODO
    });

    // Only returned for MissileLauncher turret-like items.
    // int maxMissiles
    test('to test the property `maxMissiles`', () async {
      // TODO
    });

    // Only returned for BombLauncher turret-like items.
    // int maxBombs
    test('to test the property `maxBombs`', () async {
      // TODO
    });

    // Only returned for turret-like items.
    // int minSize
    test('to test the property `minSize`', () async {
      // TODO
    });

    // Only returned for turret-like items.
    // int maxSize
    test('to test the property `maxSize`', () async {
      // TODO
    });

    // ItemDimension dimension
    test('to test the property `dimension`', () async {
      // TODO
    });

    // ItemInventory inventory
    test('to test the property `inventory`', () async {
      // TODO
    });

    // Item tags from AttachDef.
    // List<String> tags
    test('to test the property `tags`', () async {
      // TODO
    });

    // Required tags an item must match to attach.
    // List<String> requiredTags
    test('to test the property `requiredTags`', () async {
      // TODO
    });

    // Entity tag UUIDs from the database relationship (empty array when not loaded).
    // List<String> entityTags
    test('to test the property `entityTags`', () async {
      // TODO
    });

    // Entity tags from the database relationship (empty array when not loaded).
    // List<GameItemEntityTagMapInner> entityTagMap
    test('to test the property `entityTagMap`', () async {
      // TODO
    });

    // Generated from SInteractionPointParams
    // List<String> interactions
    test('to test the property `interactions`', () async {
      // TODO
    });

    // Item ports derived from stdItem.Ports.
    // List<ItemPort> ports
    test('to test the property `ports`', () async {
      // TODO
    });

    // ItemHeatConnection heat
    test('to test the property `heat`', () async {
      // TODO
    });

    // ItemTemperature temperature
    test('to test the property `temperature`', () async {
      // TODO
    });

    // ItemPowerConnection power
    test('to test the property `power`', () async {
      // TODO
    });

    // ItemDistortion distortion
    test('to test the property `distortion`', () async {
      // TODO
    });

    // ItemDurability durability
    test('to test the property `durability`', () async {
      // TODO
    });

    // ResourceContainer resourceContainer
    test('to test the property `resourceContainer`', () async {
      // TODO
    });

    // ResourceNetwork resourceNetwork
    test('to test the property `resourceNetwork`', () async {
      // TODO
    });

    // ItemEmission emission
    test('to test the property `emission`', () async {
      // TODO
    });

    // Seat seat
    test('to test the property `seat`', () async {
      // TODO
    });

    // Ammunition ammunition
    test('to test the property `ammunition`', () async {
      // TODO
    });

    // TemperatureResistance temperatureResistance
    test('to test the property `temperatureResistance`', () async {
      // TODO
    });

    // RadiationResistance radiationResistance
    test('to test the property `radiationResistance`', () async {
      // TODO
    });

    // G-force tolerance modifier. Positive values increase tolerance, negative values reduce it. 0 = neutral.
    // double gforceResistance
    test('to test the property `gforceResistance`', () async {
      // TODO
    });

    // VehicleArmor armor
    test('to test the property `armor`', () async {
      // TODO
    });

    // Cooler cooler
    test('to test the property `cooler`', () async {
      // TODO
    });

    // FlightController flightController
    test('to test the property `flightController`', () async {
      // TODO
    });

    // FuelTank fuelTank
    test('to test the property `fuelTank`', () async {
      // TODO
    });

    // FuelIntake fuelIntake
    test('to test the property `fuelIntake`', () async {
      // TODO
    });

    // HackingChip hackingChip
    test('to test the property `hackingChip`', () async {
      // TODO
    });

    // MiningLaser miningLaser
    test('to test the property `miningLaser`', () async {
      // TODO
    });

    // MiningModule miningModule
    test('to test the property `miningModule`', () async {
      // TODO
    });

    // MiningModifier miningModifier
    test('to test the property `miningModifier`', () async {
      // TODO
    });

    // Mining gadget currently resolves using the mining_module schema.
    // MiningModule miningGadget
    test('to test the property `miningGadget`', () async {
      // TODO
    });

    // QuantumDrive quantumDrive
    test('to test the property `quantumDrive`', () async {
      // TODO
    });

    // QuantumInterdictionGenerator quantumInterdictionGenerator
    test('to test the property `quantumInterdictionGenerator`', () async {
      // TODO
    });

    // SelfDestruct selfDestruct
    test('to test the property `selfDestruct`', () async {
      // TODO
    });

    // Shield shield
    test('to test the property `shield`', () async {
      // TODO
    });

    // ShieldController shieldController
    test('to test the property `shieldController`', () async {
      // TODO
    });

    // JumpDrive jumpDrive
    test('to test the property `jumpDrive`', () async {
      // TODO
    });

    // Thruster thruster
    test('to test the property `thruster`', () async {
      // TODO
    });

    // PowerPlant powerPlant
    test('to test the property `powerPlant`', () async {
      // TODO
    });

    // Radar radar
    test('to test the property `radar`', () async {
      // TODO
    });

    // ItemInventory cargoGrid
    test('to test the property `cargoGrid`', () async {
      // TODO
    });

    // GameItemClothing clothing
    test('to test the property `clothing`', () async {
      // TODO
    });

    // FPS Armor
    // SuitArmor suitArmor
    test('to test the property `suitArmor`', () async {
      // TODO
    });

    // Bomb bomb
    test('to test the property `bomb`', () async {
      // TODO
    });

    // Missile missile
    test('to test the property `missile`', () async {
      // TODO
    });

    // MissileRack missileRack
    test('to test the property `missileRack`', () async {
      // TODO
    });

    // CounterMeasure counterMeasure
    test('to test the property `counterMeasure`', () async {
      // TODO
    });

    // Emp emp
    test('to test the property `emp`', () async {
      // TODO
    });

    // PersonalWeapon personalWeapon
    test('to test the property `personalWeapon`', () async {
      // TODO
    });

    // VehicleWeapon vehicleWeapon
    test('to test the property `vehicleWeapon`', () async {
      // TODO
    });

    // MeleeWeapon meleeWeapon
    test('to test the property `meleeWeapon`', () async {
      // TODO
    });

    // Grenade grenade
    test('to test the property `grenade`', () async {
      // TODO
    });

    // MeleeWeapon knife
    test('to test the property `knife`', () async {
      // TODO
    });

    // Turret turret
    test('to test the property `turret`', () async {
      // TODO
    });

    // TractorBeam tractorBeam
    test('to test the property `tractorBeam`', () async {
      // TODO
    });

    // Food food
    test('to test the property `food`', () async {
      // TODO
    });

    // Medicine medical
    test('to test the property `medical`', () async {
      // TODO
    });

    // WeaponRack weaponRack
    test('to test the property `weaponRack`', () async {
      // TODO
    });

    // WeaponModifier weaponModifier
    test('to test the property `weaponModifier`', () async {
      // TODO
    });

    // SalvageModifier salvageModifier
    test('to test the property `salvageModifier`', () async {
      // TODO
    });

    // WeaponAttachmentIronSight ironSight
    test('to test the property `ironSight`', () async {
      // TODO
    });

    // WeaponAttachmentLaserPointer laserPointer
    test('to test the property `laserPointer`', () async {
      // TODO
    });

    // Flashlight profiles keyed by beam type (`narrow`, `wide`) when present.
    // Map<String, WeaponAttachmentFlashlightProfile> flashlight
    test('to test the property `flashlight`', () async {
      // TODO
    });

    // WeaponAttachmentMagazine magazine
    test('to test the property `magazine`', () async {
      // TODO
    });

    // WeaponAttachmentBarrelAttachment compensator
    test('to test the property `compensator`', () async {
      // TODO
    });

    // WeaponAttachmentBarrelAttachment flashHider
    test('to test the property `flashHider`', () async {
      // TODO
    });

    // ItemLink baseVariant
    test('to test the property `baseVariant`', () async {
      // TODO
    });

    // List<ItemLink> variants
    test('to test the property `variants`', () async {
      // TODO
    });

    // Only returned when `include=related_items` is requested.
    // ItemRelatedItems relatedItems
    test('to test the property `relatedItems`', () async {
      // TODO
    });

    // Deprecated: shop data is not available in the source files anymore.
    // List<Object> shops
    test('to test the property `shops`', () async {
      // TODO
    });

    // Images from external sources for this item.
    // List<GameItemImagesInner> images
    test('to test the property `images`', () async {
      // TODO
    });

    // GameItemUexPrices uexPrices
    test('to test the property `uexPrices`', () async {
      // TODO
    });

    // Only returned when `include=vehicles` is requested. Vehicles that have this item installed.
    // List<VehicleLink> vehicles
    test('to test the property `vehicles`', () async {
      // TODO
    });

    // Web URL for item detail page
    // String webUrl
    test('to test the property `webUrl`', () async {
      // TODO
    });

    // API URL for item detail endpoint
    // String link
    test('to test the property `link`', () async {
      // TODO
    });

    // Date/time this item's version-specific data was updated.
    // DateTime updatedAt
    test('to test the property `updatedAt`', () async {
      // TODO
    });

    // Game version code
    // String version
    test('to test the property `version`', () async {
      // TODO
    });

  });
}
